database:
    sql_user: postgres
    db_name: eicu
    db_password: 123456
    schema_name: eicu_crd
    sql_host: 172.16.60.173
    sql_port: 3307
section_range:
    # filter
    'PEEP filter': '[5, 25]'
    'P/F ratio filter': '(0, 300]'

    # vitalAperiodic
    'nonInvasiveSystolic': '[30,250]'
    'nonInvasiveDiastolic': '[30,150]'
    'nonInvasiveMean': '[30,150]'

    # vitalPeriodic
    'Heart rate': '[30,175]'
    'CVP': '[0, 100]'
    'etCo2': ''
    'systemicDiastolic': '[30,150]'
    'systemicMean': '[30,150]'
    'systemicSystolic': '[30,250]'
    'invasiveBPSystolic': '(0,80]'
    'invasiveBPDiastolic': '(0,40]'
    'invasiveBPMean': '(0,60]'

    # lab
    'AST (SGOT)': '[10,1000]'
    '-bands': '[0,70]'
    'bilirubin': '[0,20]'
    'calcium': '[0,50]'
    'Total CO2': '[10,45]'
    'creatinine': '[0,8]'
    'paCO2': '[10,100]'
    'potassium': '[0,12]'
    'PTT': '[20,160]'
    'SaO2': '[80,100]'
    'sodium': '[95,215]'
    'WBC': '[0,60]'
    'glucose': '[0,500]'
    'Hct': '[14,55]'
    'Hgb': '[0,16]'
    'lactate': '[0,15]'
    'Magnesium': '[0, 10]'
    'paO2': '(0,650]'
    'FiO2': '[20, 100]'
    'P/F ratio': '(0, 650]'
    'albumin': '[0, 7]'
    'platelets': '[0,1000]'
    'bicarbonate': '[5,40]'
    'BUN': '[0,115]'
    'Base Excess': ''
    'ALT (SGPT)': '[7,1000]'
    'ALP': '[0,550]'
    'pH': '[7,7.7]'
    'PT - INR': ''
    'Basos': ''
    'EOs': ''

    # nursingChartValue
    'GCS (eyes)': ''
    'GCS (intub)': ''
    'GCS (total)': ''
    'GCS (motor)': ''
    'GCS (unable)': ''
    'GCS (verbal)': ''
    'Temperature': '[30,45]'
    'SpO2': '[80,100]'
    'Respiration rate': '[1,40]'

    # respChartValue
    'Plateau Pressure': '[4,50]'
    'Peak Insp. Pressure': '[-Inf, 1000]'
    'Mean Airway Pressure': '[5,30]'
    'PEEP': '[0,25]'
    'TV/kg IBW': '[-Inf, 1000]'















































